import { RecommendedWorkout, FitnessGoal } from '../types';

export const GOAL_LABELS: Record<string, string> = {
  'lose-weight': 'Lose Weight',
  'build-muscle': 'Build Muscle',
  'run-5k': 'Run a 5K',
  'improve-endurance': 'Improve Endurance',
  'get-stronger': 'Get Stronger',
  'improve-flexibility': 'Improve Flexibility',
  'train-marathon': 'Train for a Marathon',
  'improve-health': 'Improve Overall Health',
};

export const GOAL_DESCRIPTIONS: Record<string, string> = {
  'lose-weight': 'Burn fat and shed pounds through cardio and strength training',
  'build-muscle': 'Increase muscle mass with progressive resistance training',
  'run-5k': 'Build running endurance to complete a 5K race',
  'improve-endurance': 'Boost cardiovascular fitness and stamina',
  'get-stronger': 'Increase strength and power with compound lifts',
  'improve-flexibility': 'Enhance range of motion and reduce injury risk',
  'train-marathon': 'Build the endurance to complete 26.2 miles',
  'improve-health': 'Maintain overall wellness and healthy lifestyle habits',
};

export const GOAL_ICONS: Record<string, string> = {
  'lose-weight': 'flame',
  'build-muscle': 'barbell',
  'run-5k': 'footsteps',
  'improve-endurance': 'heart',
  'get-stronger': 'fitness',
  'improve-flexibility': 'body',
  'train-marathon': 'trophy',
  'improve-health': 'leaf',
};

export const CATEGORY_LABELS: Record<string, string> = {
  strength: 'Strength',
  cardio: 'Cardio',
  running: 'Running',
  cycling: 'Cycling',
  yoga: 'Yoga',
  hiit: 'HIIT',
  flexibility: 'Flexibility',
  swimming: 'Swimming',
  other: 'Other',
};

export const RECOMMENDED_WORKOUTS: RecommendedWorkout[] = [
  {
    id: 'rw-001',
    title: 'Full Body Strength Builder',
    category: 'strength',
    durationMinutes: 45,
    difficulty: 'beginner',
    description: 'A foundational strength workout targeting all major muscle groups using compound movements.',
    targetGoals: ['build-muscle', 'get-stronger', 'improve-health'],
    exercises: [
      { id: 'e1', name: 'Squats', sets: 3, reps: 10 },
      { id: 'e2', name: 'Push-ups', sets: 3, reps: 12 },
      { id: 'e3', name: 'Dumbbell Rows', sets: 3, reps: 10, weightKg: 10 },
      { id: 'e4', name: 'Lunges', sets: 3, reps: 12 },
      { id: 'e5', name: 'Plank', sets: 3, durationSeconds: 30 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-002',
    title: 'Couch to 5K Week 1',
    category: 'running',
    durationMinutes: 30,
    difficulty: 'beginner',
    description: 'Start your running journey with alternating walk/run intervals designed for beginners.',
    targetGoals: ['run-5k', 'improve-endurance', 'lose-weight'],
    exercises: [
      { id: 'e1', name: 'Brisk Walk Warm-up', durationSeconds: 300 },
      { id: 'e2', name: 'Run 60s / Walk 90s x 8', durationSeconds: 1200 },
      { id: 'e3', name: 'Cool-down Walk', durationSeconds: 300 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-003',
    title: 'HIIT Fat Burner',
    category: 'hiit',
    durationMinutes: 25,
    difficulty: 'intermediate',
    description: 'High-intensity intervals to maximize calorie burn and boost metabolism.',
    targetGoals: ['lose-weight', 'improve-endurance', 'improve-health'],
    exercises: [
      { id: 'e1', name: 'Jump Squats', sets: 4, durationSeconds: 40 },
      { id: 'e2', name: 'Burpees', sets: 4, durationSeconds: 40 },
      { id: 'e3', name: 'Mountain Climbers', sets: 4, durationSeconds: 40 },
      { id: 'e4', name: 'High Knees', sets: 4, durationSeconds: 40 },
      { id: 'e5', name: 'Rest', sets: 4, durationSeconds: 20 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-004',
    title: 'Power Lifting Session',
    category: 'strength',
    durationMinutes: 60,
    difficulty: 'advanced',
    description: 'Heavy compound lifts to build raw strength and power.',
    targetGoals: ['get-stronger', 'build-muscle'],
    exercises: [
      { id: 'e1', name: 'Barbell Squat', sets: 5, reps: 5, weightKg: 80 },
      { id: 'e2', name: 'Bench Press', sets: 5, reps: 5, weightKg: 60 },
      { id: 'e3', name: 'Deadlift', sets: 3, reps: 5, weightKg: 100 },
      { id: 'e4', name: 'Overhead Press', sets: 4, reps: 6, weightKg: 40 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-005',
    title: 'Yoga Flow for Flexibility',
    category: 'yoga',
    durationMinutes: 40,
    difficulty: 'beginner',
    description: 'A calming yoga sequence to improve flexibility, balance, and mind-body connection.',
    targetGoals: ['improve-flexibility', 'improve-health'],
    exercises: [
      { id: 'e1', name: 'Sun Salutation A', sets: 3, durationSeconds: 120 },
      { id: 'e2', name: 'Warrior I & II', sets: 2, durationSeconds: 60 },
      { id: 'e3', name: 'Pigeon Pose', sets: 2, durationSeconds: 90 },
      { id: 'e4', name: 'Seated Forward Fold', sets: 2, durationSeconds: 60 },
      { id: 'e5', name: 'Savasana', durationSeconds: 300 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-006',
    title: 'Marathon Training Long Run',
    category: 'running',
    durationMinutes: 90,
    difficulty: 'advanced',
    description: 'A steady-state long run to build the aerobic base needed for marathon training.',
    targetGoals: ['train-marathon', 'improve-endurance'],
    exercises: [
      { id: 'e1', name: 'Easy Run', durationSeconds: 5400, distanceKm: 16 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-007',
    title: 'Beginner Cardio Blast',
    category: 'cardio',
    durationMinutes: 30,
    difficulty: 'beginner',
    description: 'Low-impact cardio to get your heart pumping without heavy joint stress.',
    targetGoals: ['lose-weight', 'improve-health', 'improve-endurance'],
    exercises: [
      { id: 'e1', name: 'Marching in Place', durationSeconds: 180 },
      { id: 'e2', name: 'Step Touches', durationSeconds: 180 },
      { id: 'e3', name: 'Low-Impact Jumping Jacks', durationSeconds: 120 },
      { id: 'e4', name: 'Knee Lifts', durationSeconds: 120 },
      { id: 'e5', name: 'Side Steps', durationSeconds: 120 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-008',
    title: 'Upper Body Hypertrophy',
    category: 'strength',
    durationMinutes: 50,
    difficulty: 'intermediate',
    description: 'Target chest, back, shoulders, and arms with volume-focused training for muscle growth.',
    targetGoals: ['build-muscle', 'get-stronger'],
    exercises: [
      { id: 'e1', name: 'Incline Dumbbell Press', sets: 4, reps: 10, weightKg: 20 },
      { id: 'e2', name: 'Cable Rows', sets: 4, reps: 12 },
      { id: 'e3', name: 'Lateral Raises', sets: 3, reps: 15, weightKg: 8 },
      { id: 'e4', name: 'Bicep Curls', sets: 3, reps: 12, weightKg: 12 },
      { id: 'e5', name: 'Tricep Dips', sets: 3, reps: 12 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-009',
    title: '5K Race Pace Intervals',
    category: 'running',
    durationMinutes: 40,
    difficulty: 'intermediate',
    description: 'Speed intervals at 5K race pace to improve lactate threshold and race performance.',
    targetGoals: ['run-5k', 'improve-endurance'],
    exercises: [
      { id: 'e1', name: 'Easy Warm-up Jog', durationSeconds: 600 },
      { id: 'e2', name: '1K at 5K Pace x 4', durationSeconds: 1200 },
      { id: 'e3', name: '400m Recovery Jog x 3', durationSeconds: 420 },
      { id: 'e4', name: 'Cool-down Jog', durationSeconds: 600 },
    ],
    source: 'built-in',
  },
  {
    id: 'rw-010',
    title: 'Active Recovery Stretch',
    category: 'flexibility',
    durationMinutes: 20,
    difficulty: 'beginner',
    description: 'Gentle stretching routine to aid muscle recovery and maintain flexibility.',
    targetGoals: ['improve-flexibility', 'improve-health'],
    exercises: [
      { id: 'e1', name: 'Hip Flexor Stretch', sets: 2, durationSeconds: 45 },
      { id: 'e2', name: 'Hamstring Stretch', sets: 2, durationSeconds: 45 },
      { id: 'e3', name: 'Quad Stretch', sets: 2, durationSeconds: 45 },
      { id: 'e4', name: 'Chest Opener', sets: 2, durationSeconds: 45 },
      { id: 'e5', name: "Child's Pose", durationSeconds: 60 },
    ],
    source: 'built-in',
  },
];

export const FITNESS_LEVELS = ['beginner', 'intermediate', 'advanced'] as const;

export const ALL_GOALS: FitnessGoal[] = [
  'lose-weight',
  'build-muscle',
  'run-5k',
  'improve-endurance',
  'get-stronger',
  'improve-flexibility',
  'train-marathon',
  'improve-health',
];
